// This file will be generated by running: flutterfire configure
//
// After setting up your Firebase project, run the following command:
// flutterfire configure
//
// This will generate the actual firebase_options.dart file with your
// Firebase project configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase configuration

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjuwXg9imkt7rhJiKnw7a_9NDIgN6vTz0',
    appId: '1:874006130232:web:dfcdc244fd9cb780afc0cd',
    messagingSenderId: '874006130232',
    projectId: 'currensee-ad1f4',
    authDomain: 'currensee-ad1f4.firebaseapp.com',
    storageBucket: 'currensee-ad1f4.firebasestorage.app',
  );

  // Run: flutterfire configure

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCePkigXKKF1YkAh_Cl7TeisS9kN2li8N4',
    appId: '1:874006130232:android:0dc08cbd4f92ad0dafc0cd',
    messagingSenderId: '874006130232',
    projectId: 'currensee-ad1f4',
    storageBucket: 'currensee-ad1f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0zKbgxy1AbbXFlnaB9_Cdx_xvO0NhPGY',
    appId: '1:874006130232:ios:0b3be56ece4f7f20afc0cd',
    messagingSenderId: '874006130232',
    projectId: 'currensee-ad1f4',
    storageBucket: 'currensee-ad1f4.firebasestorage.app',
    iosBundleId: 'com.currensee.currensee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0zKbgxy1AbbXFlnaB9_Cdx_xvO0NhPGY',
    appId: '1:874006130232:ios:0b3be56ece4f7f20afc0cd',
    messagingSenderId: '874006130232',
    projectId: 'currensee-ad1f4',
    storageBucket: 'currensee-ad1f4.firebasestorage.app',
    iosBundleId: 'com.currensee.currensee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjuwXg9imkt7rhJiKnw7a_9NDIgN6vTz0',
    appId: '1:874006130232:web:dca8337c75793d91afc0cd',
    messagingSenderId: '874006130232',
    projectId: 'currensee-ad1f4',
    authDomain: 'currensee-ad1f4.firebaseapp.com',
    storageBucket: 'currensee-ad1f4.firebasestorage.app',
  );

}